[package]
name = "rebels"
version = "1.0.0"
edition = "2021"

[profile.release]
strip = true
# lto = true
# opt-level = 3

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
uuid = { version = "1.4.1", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "serde",
] }
crossterm = "0.26.1"
rand = "0.8.5"
ratatui = { version = "0.23.0", features = ["all-widgets"] }
strum = { version = "0.21", features = ["derive"] }
image = "0.24.7"
gif = "0.12.0"
serde_json = "1.0.106"
serde = { version = "1.0.188", features = ["derive", "default"] }
rand_distr = "0.4.3"
strum_macros = "0.25.2"
itertools = "0.11.0"
futures = "0.3.28"
libp2p = { version = "0.52.3", features = [
    "noise",
    "ping",
    "tcp",
    "tokio",
    "yamux",
    "gossipsub",
    "mdns",
    "macros",
    "serde",
] }
tokio = { version = "1.34.0", features = ["full"] }
env_logger = "0.10.0"
tui-textarea = { version = "0.2.2", features = [
    "ratatui-crossterm",
], default-features = false }
void = "1.0.2"
directories = "5.0.1"
rand_chacha = "0.3.1"
serde_repr = "0.1.16"
clap = { version = "4.4.7", features = ["derive"] }
include_dir = "0.7.3"
once_cell = "1.18.0"
imageproc = "0.23.0"
rodio = "0.17.3"
chrono = "0.4.31"
unicode-width = "0.1.11"
